namespace Shady.Core
{
	public class Keycodes
	{
		public Keycodes()
		{
		}

		public static uchar keyval_to_js_keycode(uint keyval)
		{
			switch (keyval){
				case Gdk.Key.@1:
					return 0x31;
				case Gdk.Key.@2:
					return 0x32;
				case Gdk.Key.@3:
					return 0x33;
				case Gdk.Key.@4:
					return 0x34;
				case Gdk.Key.@5:
					return 0x35;
				case Gdk.Key.@6:
					return 0x36;
				case Gdk.Key.@7:
					return 0x37;
				case Gdk.Key.@8:
					return 0x38;
				case Gdk.Key.@9:
					return 0x39;
				case Gdk.Key.@0:
					return 0x30;
				case Gdk.Key.a:
				case Gdk.Key.A:
					return 0x41;
				case Gdk.Key.b:
				case Gdk.Key.B:
					return 0x42;
				case Gdk.Key.c:
				case Gdk.Key.C:
					return 0x43;
				case Gdk.Key.d:
				case Gdk.Key.D:
					return 0x44;
				case Gdk.Key.e:
				case Gdk.Key.E:
					return 0x45;
				case Gdk.Key.f:
				case Gdk.Key.F:
					return 0x46;
				case Gdk.Key.g:
				case Gdk.Key.G:
					return 0x47;
				case Gdk.Key.h:
				case Gdk.Key.H:
					return 0x48;
				case Gdk.Key.i:
				case Gdk.Key.I:
					return 0x49;
				case Gdk.Key.j:
				case Gdk.Key.J:
					return 0x4A;
				case Gdk.Key.k:
				case Gdk.Key.K:
					return 0x4B;
				case Gdk.Key.l:
				case Gdk.Key.L:
					return 0x4C;
				case Gdk.Key.m:
				case Gdk.Key.M:
					return 0x4D;
				case Gdk.Key.n:
				case Gdk.Key.N:
					return 0x4E;
				case Gdk.Key.o:
				case Gdk.Key.O:
					return 0x4F;
				case Gdk.Key.p:
				case Gdk.Key.P:
					return 0x50;
				case Gdk.Key.q:
				case Gdk.Key.Q:
					return 0x51;
				case Gdk.Key.r:
				case Gdk.Key.R:
					return 0x52;
				case Gdk.Key.s:
				case Gdk.Key.S:
					return 0x53;
				case Gdk.Key.t:
				case Gdk.Key.T:
					return 0x54;
				case Gdk.Key.u:
				case Gdk.Key.U:
					return 0x55;
				case Gdk.Key.v:
				case Gdk.Key.V:
					return 0x56;
				case Gdk.Key.w:
				case Gdk.Key.W:
					return 0x57;
				case Gdk.Key.x:
				case Gdk.Key.X:
					return 0x58;
				case Gdk.Key.y:
				case Gdk.Key.Y:
					return 0x59;
				case Gdk.Key.z:
				case Gdk.Key.Z:
					return 0x5A;
				case Gdk.Key.Alt_L:
				case Gdk.Key.Alt_R:
					return 0x12;
				case Gdk.Key.comma:
					return 0xBC;
				case Gdk.Key.period:
					return 0xBE;
				case Gdk.Key.semicolon:
					return 0xBA;
				case Gdk.Key.quotedbl:
					return 0xDE;
				case Gdk.Key.bracketleft:
					return 0xDB;
				case Gdk.Key.bracketright:
					return 0xDD;
				case Gdk.Key.grave:
					return 0xC0;
				case Gdk.Key.backslash:
					return 0xDC;
				case Gdk.Key.minus:
					return 0xBD;
				case Gdk.Key.equal:
					return 0xBB;
				case Gdk.Key.kana_RO:
					return 0xC1;
				case Gdk.Key.yen:
					return 0xFF;
				case Gdk.Key.ISO_Level3_Shift:
				case Gdk.Key.ISO_Level3_Latch:
				case Gdk.Key.ISO_Level3_Lock:
				case Gdk.Key.ISO_Level5_Shift:
				case Gdk.Key.ISO_Level5_Latch:
				case Gdk.Key.ISO_Level5_Lock:
					return 0xE1;
				case Gdk.Key.Caps_Lock:
					return 0x14;
				case Gdk.Key.Control_L:
				case Gdk.Key.Control_R:
					return 0x11;
				case Gdk.Key.Num_Lock:
					return 0x90;
				case Gdk.Key.KP_0:
					return 0x60;
				case Gdk.Key.KP_1:
					return 0x61;
				case Gdk.Key.KP_2:
					return 0x62;
				case Gdk.Key.KP_3:
					return 0x63;
				case Gdk.Key.KP_4:
					return 0x64;
				case Gdk.Key.KP_5:
					return 0x65;
				case Gdk.Key.KP_6:
					return 0x66;
				case Gdk.Key.KP_7:
					return 0x67;
				case Gdk.Key.KP_8:
					return 0x68;
				case Gdk.Key.KP_9:
					return 0x69;
				case Gdk.Key.KP_Add:
					return 0x6B;
				case Gdk.Key.KP_Separator:
					return 0xC2;
				case Gdk.Key.KP_Decimal:
					return 0x6E;
				case Gdk.Key.KP_Divide:
					return 0x6F;
				case Gdk.Key.KP_Equal:
					return 0x0C;
				case Gdk.Key.KP_Multiply:
					return 0x6A;
				case Gdk.Key.KP_Subtract:
					return 0x6D;
				case Gdk.Key.Scroll_Lock:
					return 0x91;
				case Gdk.Key.Shift_L:
				case Gdk.Key.Shift_R:
					return 0x10;
				case Gdk.Key.Super_L:
					return 0x5B;
				case Gdk.Key.Super_R:
					return 0x5C;
				case Gdk.Key.Return:
				case Gdk.Key.KP_Enter:
				case Gdk.Key.ISO_Enter:
				case Gdk.Key.3270_Enter:
					return 0x0D;
				case Gdk.Key.space:
					return 0x20;
				case Gdk.Key.Tab:
				case Gdk.Key.KP_Tab:
					return 0x09;
				case Gdk.Key.Down:
				case Gdk.Key.KP_Down:
					return 0x28;
				case Gdk.Key.Left:
				case Gdk.Key.KP_Left:
					return 0x25;
				case Gdk.Key.Right:
				case Gdk.Key.KP_Right:
					return 0x27;
				case Gdk.Key.Up:
				case Gdk.Key.KP_Up:
					return 0x26;
				case Gdk.Key.End:
				case Gdk.Key.KP_End:
					return 0x23;
				case Gdk.Key.Home:
				case Gdk.Key.KP_Home:
					return 0x24;
				case Gdk.Key.Page_Down:
				case Gdk.Key.KP_Page_Down:
					return 0x22;
				case Gdk.Key.Page_Up:
				case Gdk.Key.KP_Page_Up:
					return 0x21;
				case Gdk.Key.BackSpace:
					return 0x08;
				case Gdk.Key.Delete:
				case Gdk.Key.KP_Delete:
					return 0x2E;
				case Gdk.Key.Insert:
				case Gdk.Key.KP_Insert:
					return 0x2D;
				case Gdk.Key.Menu:
					return 0x5D;
				case Gdk.Key.Escape:
					return 0x1B;
				case Gdk.Key.Help:
					return 0x2F;
				case Gdk.Key.Pause:
				case Gdk.Key.Break:
					return 0x13;
				case Gdk.Key.3270_PrintScreen:
				case Gdk.Key.Print:
				case Gdk.Key.Sys_Req:
					return 0x2C;
				case Gdk.Key.Save:
				case Gdk.Key.F1:
					return 0x70;
				case Gdk.Key.F2:
					return 0x71;
				case Gdk.Key.F3:
					return 0x72;
				case Gdk.Key.F4:
					return 0x73;
				case Gdk.Key.F5:
					return 0x74;
				case Gdk.Key.F6:
					return 0x75;
				case Gdk.Key.F7:
					return 0x76;
				case Gdk.Key.F8:
					return 0x77;
				case Gdk.Key.F9:
					return 0x78;
				case Gdk.Key.F10:
					return 0x79;
				case Gdk.Key.F11:
					return 0x7A;
				case Gdk.Key.F12:
					return 0x7B;
				case Gdk.Key.F13:
					return 0x7C;
				case Gdk.Key.F14:
					return 0x7D;
				case Gdk.Key.F15:
					return 0x7E;
				case Gdk.Key.F16:
					return 0x7F;
				case Gdk.Key.F17:
					return 0x80;
				case Gdk.Key.F18:
					return 0x81;
				case Gdk.Key.F19:
					return 0x82;
				case Gdk.Key.F20:
					return 0x83;
				case Gdk.Key.F21:
					return 0x84;
				case Gdk.Key.F22:
					return 0x85;
				case Gdk.Key.F23:
					return 0x86;
				case Gdk.Key.F24:
					return 0x87;
				default:
					return 0x00;
    		}
		}

		public static uchar hardware_keycode_to_js_keycode(uint keycode)
		{
			switch(keycode){
				case 8:
				case 9:
					return 0x1B;
				case 10:
					return 0x31;
				case 11:
					return 0x32;
				case 12:
					return 0x33;
				case 13:
					return 0x34;
				case 14:
					return 0x35;
				case 15:
					return 0x36;
				case 16:
					return 0x37;
				case 17:
					return 0x38;
				case 18:
					return 0x39;
				case 19:
					return 0x30;
				case 20:
					return 0xBD;
				case 21:
					return 0xBB;
				case 22:
					return 0x08;
				case 23:
					return 0x09;
				case 24:
					return 0x51;
				case 25:
					return 0x57;
				case 26:
					return 0x45;
				case 27:
					return 0x52;
				case 28:
					return 0x54;
				case 29:
					return 0x59;
				case 30:
					return 0x55;
				case 31:
					return 0x49;
				case 32:
					return 0x4F;
				case 33:
					return 0x50;
				case 34:
					return 0xDB;
				case 35:
					return 0xDD;
				case 36:
				case 103:
				case 104:
					return 0x0D;
				case 37:
				case 105:
					return 0x11;
				case 38:
					return 0x41;
				case 39:
					return 0x53;
				case 40:
					return 0x44;
				case 41:
					return 0x46;
				case 42:
					return 0x47;
				case 43:
					return 0x48;
				case 44:
					return 0x4A;
				case 45:
					return 0x4B;
				case 46:
					return 0x4C;
				case 47:
					return 0xBA;
				case 49:
					return 0xC0;
				case 50:
				case 62:
					return 0x10;
				case 51:
					return 0xDC;
				case 52:
					return 0x5A;
				case 53:
					return 0x58;
				case 54:
					return 0x43;
				case 55:
					return 0x56;
				case 56:
					return 0x42;
				case 57:
					return 0x4E;
				case 58:
					return 0x4D;
				case 59:
					return 0xBC;
				case 60:
					return 0xBE;
				case 63:
					return 0x6A;
				case 64:
				case 108:
					return 0x12;
				case 65:
					return 0x20;
				case 66:
					return 0x14;
				case 67:
				case 242:
					return 0x70;
				case 68:
					return 0x71;
				case 69:
					return 0x72;
				case 70:
					return 0x73;
				case 71:
					return 0x74;
				case 72:
					return 0x75;
				case 73:
					return 0x76;
				case 74:
					return 0x77;
				case 75:
					return 0x78;
				case 76:
					return 0x79;
				case 77:
					return 0x90;
				case 78:
					return 0x91;
				case 79:
				case 110:
					return 0x24;
				case 80:
				case 111:
					return 0x26;
				case 81:
				case 112:
					return 0x21;
				case 82:
					return 0x6D;
				case 83:
				case 113:
					return 0x25;
				case 85:
				case 114:
					return 0x27;
				case 86:
					return 0x6B;
				case 87:
				case 115:
					return 0x23;
				case 88:
				case 116:
					return 0x28;
				case 89:
				case 117:
					return 0x22;
				case 90:
				case 118:
					return 0x2D;
				case 91:
				case 119:
					return 0x2E;
				case 92:
					return 0xE1;
				case 95:
					return 0x7A;
				case 96:
					return 0x7B;
				case 106:
					return 0x6F;
				case 107:
				case 217:
				case 218:
					return 0x2C;
				case 125:
					return 0x0C;
				case 127:
					return 0x13;
				case 129:
					return 0x6E;
				case 132:
				case 133:
					return 0x5B;
				case 134:
					return 0x5C;
				case 135:
					return 0x5D;
				case 146:
					return 0x2F;
				default:
					return 0x00;
			}
		}
	}
}
